-- AlterTable
ALTER TABLE "Attendance" ALTER COLUMN "checkIn" SET DATA TYPE TEXT,
ALTER COLUMN "checkOut" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Config" ALTER COLUMN "startTime" SET DATA TYPE TEXT,
ALTER COLUMN "endTime" SET DATA TYPE TEXT;
